name: Docker Image CI

on:
  push:
    branches: "develop"
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
      with: 
        ref: "develop"        
    - name: Build Docker Compose
      run: docker-compose -f custom-images/docker-compose.yml build
